name: CI workflow

# Trigger the workflow on push and pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Specify the environment where the job runs
    runs-on: ubuntu-latest

    # Use a container for the job
    container: 
      image: python:3.9-slim

    steps:
      # Step to checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Step to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step to lint the code using flake8
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      # Step to run unit tests using nose
      - name: Run unit tests with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
